# Format: RequestClass=ResponseClass:field1=field1Response,field2=field2Response

CreateUserRequest=CreateUserResponse:username=username,role=role
TransferUserDepositRequest=TransferUserDepositResponse:senderAccountId=senderAccountId,receiverAccountId=receiverAccountId,amount=amount
UpdateCustomerProfileRequest=UpdateCustomerProfileResponse:name=customer.name